spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/springdb2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

# show jdbc template sql log
logging.level.org.springframework.jdbc: debug

# Mybatis
mybatis:
  type-aliases-package: hello.itemserice.domain
  configuration:
    map-underscore-to-camel-case: true
logging.level.hello.itemservice.repository.mybatis: trace
