drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);

-- mysql
CREATE TABLE item (
                      id BIGINT AUTO_INCREMENT,
                      item_name VARCHAR(10),
                      price INT,
                      quantity INT,
                      PRIMARY KEY (id)
);